### ISSUE TITLE
Tristrips ?

### ISSUE THREAD

**Issue by Kuranes** [vilya/miniply#1]
Hi, very impressed with quality of code and performance, I have it working for basic meshes, and  would like to know more about is how to support tristrips ? 

From ply I have it's files with "element tristrips 1" but with vertex_indices with no fixed size (or to be deduced from vertex num ?

In current code I cannot get far as here "load_variable_size_element" fails because it thinks there is 1 row/count.
(https://github.com/cnr-isti-vclab/vcglib/blob/a8e87662b63ee9f4ded5d4699b28d74183040803/wrap/io_trimesh/import_ply.h#L869 )

**Comment by vilya** [comment]
Hi & thanks for the compliment! Tri-strips ought to work just like any other variable-sized element, so there must be a bug. Do you have an example file with tristrips that you can share? Or alternatively, can you copy and paste the header from one of the failing files?

**Comment by Kuranes** [comment]
Thanks for the fast anwser 
```
ply
format binary_little_endian 1.0
element vertex 2903
property float x
property float y
property float z
element tristrips 1
property list int int vertex_indices
end_header
```

[cow.zip](https://github.com/vilya/miniply/files/4508029/cow.zip)

**Comment by vilya** [comment]
Thanks for the sample file, I think I understand what's going on now. 

There's a single row in the tristrips element which contains all of the tristrips, with -1 used to indicate where a tristrip ends. Miniply doesn't have any built-in handling for that yet, so it just treats this as a single large list-valued property. To load the data from it at the moment you'll need to do something like this:
```
if (reader.element_is("tristrips")) {
  const uint32_t propIdx = reader.element()->find_property("vertex_indices");
  const uint32_t numRows = reader.element()->count;
  const uint32_t* rowCounts = reader.get_list_counts(propIdx);

  // Figure out how big an array we'll need to hold all vertex indices, including
  // the -1 tristrip terminators.
  uint32_t n = 0;
  for (uint32_t row = 0; row < numRows; row++)
    n += rowCounts[row];

  int* allTriStrips = new int[n];
  reader.extract_list_property(propIdx, miniply::PLYPropertyType::Int, allTriStrips);
  // ... do stuff with allTriStrips ...
}
```

That will give you an array, `allTriStrips`, containing all of the vertex indices from all of the triangle strips, including the -1 terminator values. If you need the data in a different form to that, then you'll have to write additional processing code yourself.

What extra methods do you think I could add to make this easier? For example, would it be useful to have a `PLYReader::extract_tristrips` method which de-stripifies the indices (i.e. turns them into something that you could use with `glDrawElements(GL_TRIANGLES, ...)`)? Or perhaps just some helper methods for iterating over the tri strips, given a terminating value?

**Comment by vilya** [comment]
I've added a new method, `PLYReader::sum_of_list_counts()`, which calculates how many values there are in total across all rows for a given list-valued property. This can be used as a more efficient replacement for the loop which calculates `n` in the example above. The example now looks like:
```
if (reader.element_is("tristrips")) {
  const uint32_t propIdx = reader.element()->find_property("vertex_indices");
  uint32_t n = reader.sum_of_list_counts(propIdx);
  int* allTriStrips = new int[n];
  reader.extract_list_property(propIdx, miniply::PLYPropertyType::Int, allTriStrips);
  // ... do stuff with allTriStrips ...
}
```

I've added similar code to the miniply-perf example too. Hopefully that'll be useful as a reference for others trying to load triangle strips.

**Comment by Kuranes** [comment]
Wow, perfect, it works. 

Thanks a lot your time and support, it sure helps a lots.

**Comment by vilya** [comment]
Glad I could help. Thanks for giving miniply a try!
