### ISSUE TITLE
find_indices() returns kInvalidIndex when file contains `vertex_index` instead of `vertex_indices`

### ISSUE THREAD

**Issue by tylermorganwall** [vilya/miniply#2]
This issue is similar to the following:

https://github.com/PointCloudLibrary/pcl/issues/968

miniply currently looks for the "vertex_indices" property, but some PLY files have this under "vertex_index" instead. This returns `kInvalidIndex` in propIdxs and results in a failure to parse.

```c++
bool PLYReader::find_indices(uint32_t propIdxs[1]) const
{
  return find_properties(propIdxs, 1, "vertex_indices");
}
```

http://paulbourke.net/dataformats/ply/ uses `vertex_index` in their examples, so it would be a good idea to check for both.

**Comment by vilya** [comment]
Fixed. Thanks a lot for pointing this out!
