### ISSUE TITLE
PLYReader::find_color - support for 'red' 'green' and 'blue' as well as 'r', 'g', and 'b'?

### ISSUE THREAD

**Issue by EdBoucher** [vilya/miniply#4]
Just doing some work with some LIDAR files, and by default they seem to have 'red', 'green' and 'blue' as the property names for colour rather than 'r', 'g', and 'b'.

I'm not really sure if this is an issue with the scanning software or not, but would it be possible to get an alternative function here, or to make the base `find_color` more robust? I've added the following to my own code, which works fine.

```
bool PLYReader::find_color_full_names(uint32_t propIdxs[3]) const
  {
    return find_properties(propIdxs, 3, "red", "green", "blue");
  }
```

Cheers,

-Ed

**Comment by vilya** [comment]
Thanks for bringing this to my attention! I think adding these names as an alternate in the existing `PLYReader::find_color()` method is probably the nicest solution? Some of the other `find_*` methods already do something similar. If you'd like to submit a PR I'd be happy to merge it, or can make the change myself if you'd prefer.

**Comment by EdBoucher** [comment]
Makes sense- I've put a PR in. Thanks!

**Comment by vilya** [comment]
I've merged it.
