### ISSUE TITLE
miniply - parse a memory buffer`

### ISSUE THREAD

**Issue by thomastong** [vilya/miniply#9]
Current it requires a file handle and must read from disk.  - so it's not very useful for parsing data transferred over a network - , can it also parse a memory buffer?  -

**Comment by vilya** [comment]
In theory miniply could be adapted for this, but I haven't needed it yet myself and don't know much about network programming, so I haven't been motivated to make the effort.

If you want to attempt it yourself, have a look at `PLYReader::refill_buffer()`. That's the main place where the file handle gets used, so I assume that's where the majority of the work to adapt it would be. `refill_buffer()` reads ~128 KB chunks from the file handle into an internal buffer & the rest of the parsing operates on that buffer, so I guess you could call a user-provided callback in there as an alternative to the `fread()` call. There's also a call to `fseek()` in `PLYReader::next_element()`, to skip past a fixed-size element which hasn't been loaded yet.

Hope that helps!

**Comment by thomastong** [comment]
I got it working as you've suggested,  I simply read everything in as a giant buffer and just pointed m_Buf to my memory buffer, bypassing refill buffer and next_element entirely. Miniply seemed to be parsing 300mb+ PLY's with no problems, so i it's stable enough, although if there's a need, I'll have a look at doing it with the callback buffer -    

You may find it interesting, i was able to include minply in to a small web-assembly project, so i was able to read in the memory via Javascript on the browser, feed it in to the minply / WebAssembly code, and read the PLY - and everything appears correct and semi-stable.  Great library, and thanks for the answer! 👍

Many loader libraries (like stbi image) for example support an an in-memory buffer decode, which makes it more flexible since often you're decoding from memory, compressed files, etc vs decoding directly off disk. - Maybe something to throw on the user request list  -
